import Cookies from 'js-cookie';
import { useRouter } from 'next/router';
import {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useReducer,
} from 'react';

import {
  getAlbumImage,
  getPlaysNumber,
  millisToMinutesAndSeconds,
} from '@/services/spotify/utils';

import { intitialState } from './initialState';
import { formReducer } from './reducer';
import { Artist, MultiStepFormContextState } from './types';
import { getParamsFromHash } from './utils';

const multiStepFormContext = createContext({} as MultiStepFormContextState);

type MultiStepFormContextProviderProps = {
  children: ReactNode;
};

export const MultiStepFormContextProvider = ({
  children,
}: MultiStepFormContextProviderProps) => {
  const [state, dispatch] = useReducer(formReducer, intitialState);

  const handleSetStep = (direction: 'prev' | 'next') => {
    const actionType = direction === 'next' ? 'INCREASE_STEP' : 'DECREASE_STEP';
    dispatch({ type: actionType });
  };

  const handleToggleArtist = (artist: Artist) => {
    dispatch({ type: 'TOGGLE_ARTIST', payload: artist });
  };

  const handleToggleGenre = (genre: string) => {
    dispatch({ type: 'TOGGLE_GENRE', payload: genre });
  };

  const generatePlaylist = async (tracksAmount = 20) => {
    try {
      const cookieAccessToken = Cookies.get('spotify_access_token');
      const requestParams = {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${cookieAccessToken}`,
        },
      };

      const preparedArtists = state.chosenArtists
        .map((artist) => artist.id)
        .join(',');
      const preparedGenres = state.chosenGenres.join(',');

      const res = await fetch(
        `https://api.spotify.com/v1/recommendations?seed_genres=${preparedGenres}&seed_artists=${preparedArtists}&limit=${tracksAmount}`,
        requestParams
      );

      const data = await res.json();

      const result = data.tracks.map((track: any) => {
        const duration = millisToMinutesAndSeconds(track.duration_ms);
        const image = getAlbumImage(track);

        // Spotify API doesn't share information about track plays number.
        // For development reasons it is a random number generated by track popularity.
        // Popularity is value between 0 and 100, with 100 being the most popular.
        const playsNumber = getPlaysNumber(track.popularity);
        const mainArist = track.artists[0];

        return {
          id: track.id,
          name: track.name,
          author: mainArist.name,
          image,
          duration,
          playsNumber,
        };
      });

      dispatch({ type: 'ADD_TRACKS', payload: result });
      handleSetStep('next');
    } catch (err) {
      console.log(err);
    }
  };

  const router = useRouter();

  useEffect(() => {
    const params = getParamsFromHash(router.asPath);
    if (!params.access_token || !params.expires_in) return;

    const { access_token, expires_in: expiresTimeInSeconds } = params;
    const expireDate = new Date(
      new Date().getTime() + Number(expiresTimeInSeconds) * 1000
    );

    Cookies.set('spotify_access_token', access_token, { expires: expireDate });
    dispatch({ type: 'SET_STEP', payload: 2 });
  }, [router.asPath]);

  useEffect(() => {
    const cookieAccessToken = Cookies.get('spotify_access_token');
    if (cookieAccessToken && state.currentStep === 1) {
      dispatch({ type: 'SET_STEP', payload: 2 });
    }
    dispatch({ type: 'SET_LOADING', payload: false });
  }, [state.currentStep]);

  const values = {
    ...state,
    handleSetStep,
    handleToggleArtist,
    handleToggleGenre,
    generatePlaylist,
  };

  return (
    <multiStepFormContext.Provider value={values}>
      {children}
    </multiStepFormContext.Provider>
  );
};

export const useMultiStepFormContext = () => {
  const value = useContext(multiStepFormContext);
  if (!value) throw new Error('Context provider is not initialized');
  return value;
};
